### PR TITLE
Add smiley " :B "

### PR DESCRIPTION
**Pull request by A-312**
Cf. https://github.com/zestedesavoir/zds-site/pull/4951#issuecomment-410361589

### CODE REVIEW

**Comment by pierre-24** [comment]
It does now : https://github.com/zestedesavoir/zds-site/pull/4951/files 

... But I see the problem here: since zmarkdown is released more often than zds, it may cause issues ?

**Comment by vhf** [comment]
Yep, zmarkdown doesn't follow zds releases. This smiley won't get merged before it actually exists, to make sure it exists I'll click on the link. If it shows a smiley, the smiley exists on zds, if it's a 404 then the smiley does not exist.

**Comment by pierre-24** [comment]
It's a bit of a chicken-and-egg situation, but ok, I added a reminder for the next release ^^

**Comment by vhf** [comment]
Not that much, there's a precise order in which to do this. If we released this here before zds, we would end up with something like this whenever somebody type `:B`

**Comment by artragis** [comment]
here?

**Comment by pierre-24** [comment]
I don't get why we still get a 404, even though that should be deployed in production ... o_O ?

**Comment by artragis** [comment]
as far as I see it's only deployed on beta (will be added in v27.3)

**Comment by pierre-24** [comment]
Ah, ok, I thought it was older than that ^^

**Comment by A-312** [comment]
:B

**Comment by A-312** [comment]
Ready

**Comment by vhf** [comment]
I'll do this after https://github.com/zestedesavoir/zds-site/issues/5111

**Comment by A-312** [comment]
@vhf #5111 is merged

**Pull request merged**
