### PR TITLE
Ajout d'un plugin filtrant les schemas des URIs

### PR DESCRIPTION
**Pull request by arobase-che**
Coucou \o

Comme promis. Besoin d'une revue. #chezmoiçamarche  
Là seule chose que j'ai pas testé il me semble c'est un réinstallation totale.

À bientôt je pense.

### CODE REVIEW

**Comment by vhf** [comment]
A few comments:

* Nothing gets merged without a clear explanation of why it's needed and how it works.
* Tests need to pass.
* The name of the thing you're trying to add to this project doesn't make enough sense for me to understand the idea.

**Comment by arobase-che** [comment]
Hi \o

The goal of this PR is to protect zmarkdown from XSS URI.
Currently, XSS URI is possible with zmarkdown.

Try that link : 
~~~md
[Cool link try it out](javascript:console.log(alert("Ahaha i'm evil ! 😈  ")))
~~~

I will check the problem of the PR tonight.

**Comment by vhf** [comment]
What is "remark-seclink", how does it prevent the issue?

**Comment by arobase-che** [comment]
It works by whitelisting only some URI schemes.

remark-seclink, is a remark plugin created for this purpose. Thus, i can rename it, or it can be merged into the zestedesavoir repository.

XSS URIs seem to be dangerous security problem.   
I will try to fix the PR a soon as possible. It looks like a dependencies problem. 

Sorry about my english ._.

**Comment by vhf** [comment]
Whitelisting URL schemes is a good approach but the issue you describe has to do with HTML. Some remark plugins generate elements that aren't anchors yet get rendered as HTML anchors. For instance `ping` elements will become HTML anchors and these won't go through your plugin.

HTML anchors are not the only elements for which this type of XSS are possible either, HTML img also seem to be affected: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Image_XSS_using_the_JavaScript_directive

For these reasons I don't think this is related to `link` and I don't think this should be a `remark` plugin. If you want to tackle this issue, a rehype plugin would probably be safer and naming it something like `rehype-url-scheme-whitelist` would be much more explicit than `remark-seclink`.

I recommend writing a good README including at least _why (this plugin)_ and _how (this plugin works)_; a good test suite would also be nice.

**Comment by arobase-che** [comment]
Ok.

I have already checked and 
~~~html
<IMG SRC="javascript:alert('XSS');">
~~~
Doesn't seem to work anymore on modern browsers.


They is already a whitelist approach on the media tag : 
~~~md
!(https://www.youtube.com/watch?v=SoLCD3rP9DM)
~~~
A `startBy("http")` is present.

I will follow your advices. Maybe it's important to deal with older browsers who still affected by img's src XSS.

**Comment by arobase-che** [comment]
k

**Comment by arobase-che** [comment]
I will work on a rehype plugin instead of a remark plugin as it's a HTML issue. ;) 

Now that i can see the tests that fails, how should i handle : 
~~~shell
    Expected value to be:
      "<p><a href=\"path/to/image.png\"><img alt=\"altname\" src=\"path/to/img_thumb.png\"></a></p>"
    Received:
      "<p><a href=\"/path/to/image.png\"><img src=\"path/to/img_thumb.png\" alt=\"altname\"></a></p>"
    Difference:
    <p><a href="/path/to/image.png"><img alt="altname" src="path/to/img_thumb.png"></a></p>
~~~

I think, that we should update the tests, shouldn't we ?

**Comment by A-312** [comment]
```js
if (link.url.indexOf(":") !== -1)
```

But this will catch `mypage.html?a=user:1234`, usually ":" should be encoded with : "%20" like this :  `mypage.html?a=user%201234`

An other way : 

```js
function plugin() {
  return transformer;
  function transformer(tree) {
    visit(tree, 'link', link => {
      if (link.url) {
        if (['/', './', '../'].some(link.url[0])) { // Local link
          return;
        }

        try {
          const url = new URL(link.url);

          if (schemes.some(scheme => url.protocol === scheme + ':')) {
            return;
          }
        } catch (e) { }

        link.url = '/' + link.url;
      }
    });
  }
}
```

**Comment by vhf** [comment]
> we should update the tests, shouldn't we ?

I don't think so, they look fine to me. You should only take care of links that have a scheme.

**Pull request closed without merging**
