### PR TITLE
Remark-caption readme

### PR DESCRIPTION
**Pull request by artragis**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks!

Here is how it looks with this PR: https://github.com/artragis/zmarkdown/blob/c976e354123ae64b72f0af4a62be377f4bc857f0/packages/remark-captions/README.md and how it should look like: https://github.com/zestedesavoir/zmarkdown/blob/ba8d1ca0509c77d4afc800771543d4a9463332bf/packages/remark-ping/README.md

Key differences:

* Badges and heading missing
* unparsed headings
* issues with fenced code block
* missing link references
* missing license at the end

**Comment by artragis** [comment]
> issues with fenced code block

which one please?

**Comment by vhf** [comment]
Sorry about that, I went too fast and didn't notice it was an example :/

**Comment by vhf** [comment]
👍

**Pull request merged**
