### PR TITLE
remark-abbr: optionally expand first occurrence inline

### LINKED ISSUE #304: Option to have remark-abbr substitute definition for first occurrence.
In written documents, it's [common](https://blogs.millersville.edu/bduncan/abbreviations-2/) for the first occurrence of an abbreviation to be introduced with the definition first followed by the abbreviation in brackets. It would be great if the `remark-abbr` plugin could optionally do this. e.g.

```markdown
This plugin works on MDAST.

More stuff about MDAST.

*[MDAST]: Markdown Abstract Syntax Tree
```

Would translate to:
```html
<p>This plugin works on Markdown Abstract Syntax Tree (MDAST).</p>

<p>More stuff about <abbr title="Markdown Abstract Syntax Tree">MDAST</abbr>.</p>
```

This would be especially great for workflows where documents are being composed of multiple markdown files and it's not immediately obvious which file will be introducing a given abbreviation first.

### PR DESCRIPTION
**Pull request by roxspring**
Given the markdown:
```markdown
This plugin works on MDAST.

More stuff about MDAST.

*[MDAST]: Markdown Abstract Syntax Tree
```

Then, with options of `{expandFirst: true}`, the plugin would translate to the following:

Would translate to:
```html
<p>This plugin works on Markdown Abstract Syntax Tree (<abbr title="Markdown Abstract Syntax Tree">MDAST</abbr>).</p>

<p>More stuff about <abbr title="Markdown Abstract Syntax Tree">MDAST</abbr>.</p>
```

Note that this is not quite as spec'd in #304 since the "(MDAST)" in the initial expansion also gets recursively expanded. This wasn't intentional, and I haven't spotted how to avoid it, but I'm not sure it's awful behaviour either!

Opening a WIP pull request to get feedback on behaviour and implementation. Assuming positive response I'll update with documentation of the new functionality in README.md.

Closes #304

### CODE REVIEW

**Comment by roxspring** [comment]
Addressed @houndci-bot complaints. 

Not clear whether the @traviscibot issues are introduced by my code changes - advice welcome!

**Comment by vhf** [comment]
@roxspring Looks good to me, that's definitely a useful feature! 👍 

Please go ahead with the README update, I'll fix the failing tests (not your fault, no idea why cyrillic tests suddenly fail).

**Comment by vhf** [comment]
Thanks, merged via 4915e3b2b0dfeddf8739f735a6a68a32c23ccc45

I'll work on a release next week and will ping you here once released

**Comment by vhf** [comment]
@roxspring Here we go https://www.npmjs.com/package/remark-abbr/v/1.3.0 :)

**Pull request closed without merging**
