### PR TITLE
remark-abbr: TypeScript type definitions

### PR DESCRIPTION
**Pull request by LukeCarrier**
This PR is a follow on from the query in https://github.com/zestedesavoir/zmarkdown/issues/384#issuecomment-706429418

I've added TypeScript definitions (ambient modules) for the `remark-abbr` module, and ensured that they're published as part of `npm pack`.

I wasn't quite sure how best to test the definitions as part of your dev/test workflow, but I've included a configuration for `dtslint` which runs as part of `test`. Feedback welcome!

### CODE REVIEW

**Comment by TitiAlone** [comment]
I hadn't look at it in depth yet, but I was expecting these to go in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository instead of this repository. I mentioned it in [my reply on your comment](https://github.com/zestedesavoir/zmarkdown/issues/384#issuecomment-707665027), but maybe didn't made it clear. Do you think there's a need to have them inside this repo instead of using DefinitelyTyped?

**Comment by LukeCarrier** [comment]
It was easier to get them working here, as to get them into DefinitelyTyped we. We'd to get a couple of dependencies (`remark-abbr` and `unified`) whitelisted in their linting tool, as by default only packages in DT itself are available.

I'm happy to move them into DT if you prefer; sorry for glossing over that point.

**Comment by TitiAlone** [comment]
If that's not a problem for you, I'd prefer them in the DefinitelyTyped reporistory. Don't know what would work better: should I review the typings here, so that you can put them directly on DT, or you can mention me in your PR on their side to get a review.

Anyway, I'll keep this PR opened to keep track of it, and close it when typings are merged into DT.

**Comment by LukeCarrier** [comment]
I'll link the PRs in DT once they're open 🙂

**Comment by LukeCarrier** [comment]
I've raised the two PRs:

* DefinitelyTyped/DefinitelyTyped#49069 contains the new type definitions.
* microsoft/DefinitelyTyped-tools#132 adds `remark` and `unified` to the `package.json` whitelist, and should fix the failing CI job. This is necessary because both packages ship their type definitions in their NPM packages rather than via DT.

**Comment by TitiAlone** [comment]
I see the two PRs have been merged. Is everything fine or do we need to do something here?

**Comment by LukeCarrier** [comment]
No action necessary 😃

**Comment by TitiAlone** [comment]
Thanks once more for the work done!

**Pull request closed without merging**
